### ISSUE TITLE
New UI to navigate instances for a specific ontology

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#119]
For a given ontology, add a tab to visualize instances
ah will have the following URL: 
http://agroportal.lirmm.fr/ontologies/TRANSMAT?p=instances

Pagination might be necessary.

**Comment by jonquet** [comment]
Compared to #118 this FR is about visualizing all the instances of an ontology in a simppel page, with pagination with links back to the specific class. 
I see it as a new tab at the right of "Mappings" and before "Widget"
<img width="228" alt="Capture d’écran 2021-10-15 à 15 01 46" src="https://user-images.githubusercontent.com/7379183/137491031-65131adf-8829-4e17-8741-db1c089133ba.png">

The page would display a paginated list of instances like : 
Instance1 [Class1]
Instance2 [Class1]
Instance3 [Class2]
with the [Class] text being a link to the corresponding class web page.
The REST call to follow to produce the page is given above in the issue.

**Comment by jonquet** [comment]
This feature need to be implemented in a way that OntoPortal can take it back (pull request on NCBO GitHub planned).
FYI to @mdorf @jvendetti and @graybeal

**Comment by graybeal** [comment]
I'd put it right after Classes. It has way more to do with classes than mappings or widgets.

A suggestion is that if the instance is also represented in the Class tree, it get a star or something. (The SKOS ontologies the instances will be in the class tree, because BP handles it; for other ontologies it will not be true, unless it has been explicitly punned within the ontology.)

Thank you for the guideline to implement it so we (BP) can use it. Aside from starting with an up-to-date OntoPortal fork, I think that mainly means follow the UI pattern you see in the Classes tab. But Jennifer may have something to add that would be helpful.

**Comment by syphax-bouazzouni** [comment]
Todo : 

- [ ] Implement ontology class instances pagination https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/2
- [ ] Create ontology instances new tab in bioportal web ui 
- [ ] Create ontology class instances new tab in bioportal web ui

**Comment by jonquet** [comment]
@graybeal @mdorf @jvendetti
This is released in AgroPortal. Please have a look for possible future integration.
