### ISSUE TITLE
Update the metadata 'includedInDataCatalog'

### ISSUE THREAD

**Issue by antool** [agroportal/project-management#120]
BioSharing is now FAIRsharing (see http://aims.fao.org/activity/blog/biosharing-now-fairsharing-discover-and-add-standards-databases-and-policies).
Change the logo 'BioSharing' into 'FAIRsharing' in the summary page of the ontology

**Comment by syphax-bouazzouni** [comment]
@jonquet to close ?

**Comment by jonquet** [comment]
No. 
We need to change this little line of code so that the following  button : 
<img width="351" alt="image" src="https://user-images.githubusercontent.com/7379183/197788132-7be23ee6-ae0d-49eb-8d22-7f901f7dbebe.png">

Got transformed into a simple button on which only "FAIRsharing" is written.

**Comment by syphax-bouazzouni** [comment]
Fixed with https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/184
<img width="755" alt="image" src="https://user-images.githubusercontent.com/29259906/216941636-9fdbf1ff-eb04-410c-96f7-97bf929fbb63.png">

But it is still not configurable, the list of possible data catalogs are hard coded in the code here https://github.com/ontoportal-lirmm/bioportal_web_ui/blob/fdcf1538c9fca6ffa85fb154e90dfbb9e3f25340/app/controllers/application_controller.rb#L33 nad can be extracted in the future in the configuration files

**Comment by jonquet** [comment]
Ultimatly, we could use the same list of catalogues than in O'FAIRe here : 
https://github.com/agroportal/fairness/blob/master/src/main/resources/config/common/catalogs.config.json

Ok to close this, still I would ask @hibadjebabria169 to review all the values of the includedInDataCatlog properties and see if we need to update the code again to avoid the UI to display URLs in this section.

**Comment by jonquet** [comment]
@hibadjebabria169 News? 
Can you list the values that are not resolved by the UI as a button ?
