### ISSUE TITLE
Change the submission parsing to automatically extract mappings described inside ontologies

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#122]
Open to track the work done to change BioPortal/AgroPortal submission parsing process to automatically extract standards mappings (or mappings based on a property specified at upload time). 

Right now if an ontology file contains "mappings" represented with SKOS matching properties or owl:sameAs or any other specific property (e.g., OBO-XREF, SIO properties), those mappings will not be extracted by AgroPortal. There are multiple historical reasons for this (not described here).
Now that we have changed AgroPortal's internal mapping component and allowed 'external mappings', the situation is slightly different and we can implement a mapping extraction step when parsing an ontology.

Cf: https://github.com/agroportal/documentation/wiki/Mappings for more information on Mappings

**Comment by syphax-bouazzouni** [comment]
@jonquet this requirement needs to be updated or closed.

The title "Change the submission parsing to automatically extract mappings described inside ontologies" is already implemented.

Still, your description is more about extracting mappings from the ontology axioms (like described here #66 ), which is not implemented yet.

A good thing to do is to regroup all the old mappings issues/features-request/plans in a new issue that we plan to do next year. otherwise, we will lose them.

**Comment by jonquet** [comment]
This has been implemented (v1) with #302
Note that only SKOS mapping properties have been added. owl:sameAs and oboInOwl:hasDbXref has not.
