### ISSUE TITLE
Annotator returns multiple annotations with "number"

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#132]
Try with Cassava Ontology

**Comment by syphax-bouazzouni** [comment]
is it still relevant @jonquet?

**Comment by jonquet** [comment]
![image](https://github.com/agroportal/project-management/assets/7379183/2f1996dc-71fe-4314-ad32-3cceae68f192)

Yes it is. Certainly an issue with redis dictionary

**Comment by syphax-bouazzouni** [comment]
I think it is the same issue as https://github.com/agroportal/project-management/issues/572, Cassava Ontology has multiple zombie graphs
![image](https://github.com/agroportal/project-management/assets/29259906/3b399fde-dd3c-4e95-822f-4b133271d39c)

**Comment by syphax-bouazzouni** [comment]
Removed the zombie graphs and re-run the generated dictionary script.

But we still see the "numbers" lines in that annotation results. Because this ontology define `Number` concept multiple time 
![image](https://github.com/agroportal/project-management/assets/29259906/aed5e0d5-5289-45f4-a743-cf249d72155b)
