### ISSUE TITLE
see why NCBITAXON is not parsing

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#191]
For information it don't work also in NCBI bioportal
![image](https://user-images.githubusercontent.com/29259906/151205013-c43b8e31-ae5d-4f05-a62b-75c86cf5cb45.png)

**Comment by syphax-bouazzouni** [comment]
related https://github.com/ncbo/ontologies_linked_data/issues/124, https://github.com/ncbo/bioportal-project/issues/228
The NCBO folks thinks it is a heap size memory problem.

**Comment by jonquet** [comment]
Certainly fixed in BioPortal with new heap size setting. Thus can be tested again with the new heap-size parametrized setting (https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/15)

**Comment by syphax-bouazzouni** [comment]
Retry after https://github.com/ncbo/ontologies_linked_data/issues/124 and https://github.com/ncbo/goo/pull/122

The Result is an error : "file not found in https://data.bioontology.org/ontologies/NCBITAXON/download?apikey=..."

There is a special handler for UMLS files

**Comment by syphax-bouazzouni** [comment]
Changing the format from UMLS to OWL did fix the issue 

![Image](https://github.com/agroportal/project-management/assets/29259906/9999b9a9-62f5-4f06-8f7a-0146ec8a7f95)

**Comment by syphax-bouazzouni** [comment]
FYI @naouelkaram

**Comment by naouelkaram** [comment]
Hi @syphax-bouazzouni, do you know why the Classes are also Individuals? you can see it in the metrics and also on the raw data of the classes.
![NCBITAXON-Metrics](https://github.com/agroportal/project-management/assets/7716169/a6abbdeb-1ae9-4052-aeee-57c9f49bfc69)
![NCBITAXON-ClassIndividual](https://github.com/agroportal/project-management/assets/7716169/f37507aa-5d47-40d8-9898-1bde64bd19c5)

**Comment by jonquet** [comment]
This need some investigation indeed. 
Seeing the ressource as an OWL file on our side has enabled parsing, but the result in the tree hiearchy is not good. We have stuff that should not be there as top concepts.
I would suppose the OWL-API also ends up counting every classes an instances too.

**Comment by naouelkaram** [comment]
Definitely @jonquet, I did an initial investigation on the BioPortal ttl version and I suspect the issue comes from the use of umls:hasSTY which is an ObjectProperty so the OWL-API classified all classes also as individuals. Also the top concepts appearing in Agroportal are not classified, they are also in BioPortal, they just do not appear in the hierarchy until you search for them, like this one: [http://purl.bioontology.org/ontology/NCBITAXON/374660](http://purl.bioontology.org/ontology/NCBITAXON/374660).
There are SKOS Classes (Concept, etc...) because the ontology imports skos.
And finally, the URIs are different from the OBO ones: http://purl.bioontology.org/ontology/NCBITAXON/374660 instead of http://purl.obolibrary.org/obo/NCBITaxon_374660
