### ISSUE TITLE
EFO can't process because /srv/ontoportal/data/repository/EFO/39/efo.owl is not found

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#207]
![image](https://user-images.githubusercontent.com/29259906/153381731-500b3f1c-7909-4161-8634-0028df90c172.png)

**Comment by jonquet** [comment]
Strange but indeed the file is not here, like if it as deleted. 
Certainly because the folder is not writable for user ontoportal

![image](https://user-images.githubusercontent.com/7379183/153383472-63049c78-f3e9-4a59-a185-c26f96f075c4.png)

- [x] Fix the access right to folder on server 
- [x] Relocate EFO 3.7 file somewhere and re-upload it
- [x] Identify pullLocation URL if available
- [x] Assess important missing versions of EFO in AgroPortal and possibly load them
- [x] Resubmit the last version of EFO as a new submission

**Comment by jonquet** [comment]
EFO releases are listed here : https://github.com/EBISPOT/efo/releases?page=5
We are missing since 2.106 assuming we don't know what's the latest one. 
![image](https://user-images.githubusercontent.com/7379183/153425250-c10067e2-e74c-4b3b-9284-9525c8156235.png)

**Comment by jonquet** [comment]
It seems last vrsion in AgroPOrtal is 3.7 which is available here : https://github.com/EBISPOT/efo/releases/download/v3.7.0/efo.owl

@syphax-bouazzouni uses this to test #190 
(download the 3.7 file from GitHub and re-upload it manually to AgroPortal) 

After #190 is fixed, we will skip all the version beteem 3.7 and 3.38. That's life.

PullLocation URL to reuse at the end is https://github.com/EBISPOT/efo/releases/download/current/efo.owl

**Comment by jonquet** [comment]
Done. 
Added @zoependlington to user mailing list.
