### ISSUE TITLE
Search test done is inconsistent as it test deprecated or multilingual classes that are not indexed

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#223]
We can assume the Search test done by the diagnostic script is inconsistent as it tests on classes that are not indexed such as deprecated ones or classes with label in another language. 

In AgroPortal, check out DSW report : 
<img width="204" alt="image" src="https://user-images.githubusercontent.com/7379183/154737809-3d518bb7-444c-4297-9873-2a967e6767e4.png">

The 3 concepts tested in red are declared deprecated in the source file.

**Comment by jonquet** [comment]
Same situation occur with classes for which there is only a label tagged with another language tag than english. They are used for test but are not indexed. 
For instance ASCOPAIN-T in AgroPortal 

<img width="145" alt="image" src="https://user-images.githubusercontent.com/7379183/154738071-f29dd9cf-4dd3-4e7f-bf74-f37daad7f020.png">

**Comment by jonquet** [comment]
@mdorf @jvendetti @graybeal for information

**Comment by syphax-bouazzouni** [comment]
## Multilingual classes indexation 
After more investigation in the case of multilingual classes, **prefLabel are not indexed** 
And they are not indexed because this [function that fetch the prefLabel attribute (and others) from the store](https://github.com/ontoportal-lirmm/ontologies_linked_data/blob/master/lib/ontologies_linked_data/models/ontology_submission.rb#L2045) return an empty array in the case  of multilingual class. 
We can verify this in CSV files (that contains the same attributes that are indexed) : 

- For the case of an english class (e.g [ATC](http://data.agroportal.lirmm.fr/ontologies/ATC/download?apikey=3aea6996-bb79-44c9-93c6-b2cef64f5f66&download_format=csv)), we see that the column **prefLabel** is filled 
![image](https://user-images.githubusercontent.com/29259906/155662885-6e86aba9-0c9e-45fc-8477-d17ee8066d7f.png)
- While for the case of a french class (e.g  [ASCOPAIN-T](http://data.agroportal.lirmm.fr/ontologies/ASCOPAIN-T/download?apikey=3aea6996-bb79-44c9-93c6-b2cef64f5f66&download_format=csv)) , we see that column prefLabel (and some others) is(are) empty
![image](https://user-images.githubusercontent.com/29259906/155663180-545ae6bd-cfff-4364-9ab5-fbc197d89e48.png)

### Where does the bug come from 
I think that it's related to changes made by Vincent in implementing a multilingual portal (for sifrbioportal) ([see compare](https://github.com/ncbo/goo/compare/master...ontoportal-lirmm:master))
![image](https://user-images.githubusercontent.com/29259906/155664102-6c49ac5e-f2cf-45c4-a23d-64c2e30aa712.png)

### To do
Fix the function [self.map_attributes](https://github.com/ontoportal-lirmm/goo/blob/master/lib/goo/base/resource.rb#L232)

## Deprecated classes indexation 
https://github.com/agroportal/documentation/issues/222

**Comment by syphax-bouazzouni** [comment]
fixed by https://github.com/ontoportal-lirmm/goo/issues/6 and https://github.com/ontoportal-lirmm/goo/issues/8
