### ISSUE TITLE
Refactor Ontoportal UI

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#287]
## Goals

- Fluent UI
- Simple and beautiful UI 
- Have a better UX 
- Use modern technologies (remove the technical debt)
- Have composable UI 

## Requirements 

- [x] A state of the art of existent vocabulary repositories ( [skosmoos](https://consultation.vocabulaires-ouverts.inrae.fr/thesaurus-inrae/fr/groups), https://smt.esante.gouv.fr/  , [showvoc](https://stats.fao.org/caliper/browse/showvoc/#/datasets) , [ols](https://www.ebi.ac.uk/ols/ontologies) ,...) 
- [x] An overview of all our views (see https://stageportal.notion.site/Agroportal-UI-views-update-b7fce3963b6b45afac91ce105c37ba46)
- [x] A new design (link to the Figma: figma.com/file/n2tOIfgVlVvFAr3F00Ab5m/Ontoportal-alliance?type=design&node-id=9-19&t=opySG6l9gVeKTpwC-0#383784491)
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/130#issue-1496830855
- [ ] [Migrate our old (JS) code to Hotwire](https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/426)
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/243
- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/275
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/222
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/223
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/75
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/86
- [x] https://github.com/agroportal/project-management/issues/295
- [x] #313
- [x] https://github.com/agroportal/project-management/issues/35
- [x] How to make the UI easily customizable (have a theme system, with a configuration file, or in real-time with a UI)
- [x] Do the ontoportal products landing page (see https://jekyllthemes.io/theme/hydra-jekyll-theme) (see https://ontoportal.org/)
- [x] https://github.com/agroportal/project-management/issues/321#issuecomment-1353559083
- [x] https://github.com/agroportal/project-management/issues/333
- [x] https://github.com/agroportal/project-management/issues/303
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/67
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/224
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/24

## Documentation
- [Build the UI development environment](https://doc.jonquetlab.lirmm.fr/share/f3aece4e-47a2-4fa0-9924-47bccb1f062a)
- [Learn Hotwire ](https://www.hotrails.dev/turbo-rails) and [how to do progressive Enhancement](https://boringrails.com/articles/thinking-in-hotwire-progressive-enhancement/)
- [Migrating to bootstrap v5 ](https://getbootstrap.com/docs/5.0/migration/)
- Related https://github.com/ncbo/bioportal_web_ui/pull/201 and https://github.com/ncbo/bioportal_web_ui/pull/223
- https://viewcomponent.org/

**Comment by Bilelkihal** [comment]
**Competitive Analysis**
Competitive analysis is an assessment of the strengths and weaknesses of current and potential competitors. 
This analysis provides both an offensive and defensive strategic context to identify opportunities and threats. 
We have selected four ontology repositories for this analysis (Skosmos, ANS, ShowVoc, OLS). 
In order to benefit from these ontology repositories, we are looking for features that are missing from our 
application (Agroportal), and the details that can improve the user experience. Furthermore, we strive to avoid 
their faults in the future.
![table](https://user-images.githubusercontent.com/61744974/202928387-8954bde3-fe40-4ee7-bb0b-7eecaa0ea4a0.png)
![graphe](https://user-images.githubusercontent.com/61744974/202928393-12b12fcc-db7c-4dd9-975a-8ce0b67480dc.png)


**Notes**
- All competitors provide the possibility of browsing the ontologies, but it's not well organized and not easy 
to use.
They have to think about a more creative way to display ontologies in a simple and organized way.
This part of the application should be given more importance.
-  They used old visual elements (which are the default framework/technology elements).
They have to use visual elements similar to the ones that users are using on other websites in 2022.
-  For the search feature, the auto-complete is neglected, as well as the advanced search in some of these 
applications.
A performant auto-complete must be provided, as well as thinking more about the filters used in 
the advanced search.
- Multilingualism is recommended because it makes the app target more people around the world.
- Ontologies should be organized into groups and categories to make it easy to browse them.
- There are some features in which we need the user to have an account.
- Providing the possibility of downloading the ontologies in different formats is recommended.
- It is recommended to provide documentation or help to the users.
- Providing the possibility of making SPARQL requests directly on the website is a good plus.
- Showing ontologies in a graph helps a lot in visualizing them.
- Providing the users the possibility to give their feedback on the app helps make it better in the 
future.
-  The emails sent from this website (like inscription confirmation mail) should be given the same visual 
identity as the website, not just plain text.

**Comment by jonquet** [comment]
Hello. You can also have a look at : 

http://aber-owl.net/
https://ontobee.org/
https://bartoc.org/
https://lov.linkeddata.es/
https://mmisw.org/
https://www.hetop.eu
https://ontohub.org/
https://vocabs.ardc.edu.au/

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/7379183/200894598-3bd28902-b5df-40b8-82a1-0e6f2f561759.png">

**Comment by syphax-bouazzouni** [comment]
https://github.com/agroportal/project-management/issues/287#issuecomment-1309068728 Source : https://fr.slideshare.net/jonquet/ontology-repository-and-ontologybased-services

**Comment by syphax-bouazzouni** [comment]
Special note for

- https://ontohub.org/ it is written in Ruby on Rails, so maybe can reuse some of their features (e.g visualization)
- https://www.hetop.eu and their system of multi-languages

**Comment by syphax-bouazzouni** [comment]
Done for most of the important views, starting from release[ 2.7.0](https://github.com/ontoportal-lirmm/bioportal_web_ui/releases/tag/v2.7.0) to [2.8.0](https://github.com/ontoportal-lirmm/bioportal_web_ui/releases/tag/2.8.0).

The remaining UIs are listed [here](https://docs.google.com/spreadsheets/d/1atQ1ZICUfj9EgcO33Eiqp_bzBR7MQxB8/edit?pli=1#gid=1797396029)
