### ISSUE TITLE
Harmonize, correct and generalize the terminology used by the user interface 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#321]

**Comment by jonquet** [comment]
The issue is about the words/terminology used within AgroPortal that are inherited from BioPortal that was originally developped "for ontologies". 
Now we want to harmonize, correct and generalize the terminology used within the user interface to encompass more than ontologies: 
- Use the word "semantic resource" instead of "ontologies 
- Ue the word "classes or concepts" instead of "classes" only 
- Other example to come

**Comment by syphax-bouazzouni** [comment]
See also https://ecoportal.lifewatch.eu/ work on that

**Comment by syphax-bouazzouni** [comment]
Done  https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/449
