### ISSUE TITLE
Complete Agroportal metamodel 2023

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#339]
### Context

We have implemented 2018, significant changes (compare to the NCBO BioPortal) in terms of ontology metadata. This is explained in a publication in Data Semantics Journal: https://doi.org/10.1007/s13740-018-0091-5

A new metadata mode was implemented to support better descriptions of ontologies and their relations with respect to the standards metadata vocabularies used in the semantic web community. We have reviewed the most standard and relevant vocabularies out there to describe metadata for ontologies (such as Dublin Core, VoID, Ontology Metadata Vocabulary, Data Catalog Vocabulary, etc.) 

Technically most of the work was: 

- Updating the Ontology Submission model
- Add metadata extraction process
- Update Goo to set metadata attributes for the properties  (e.g helpText, metadataMappings,  extractedMetadata(boolean), ...)

The new metadata model can be seen here http://data.agroportal.lirmm.fr/submission_metadata

A[ video presentation was done in 2018](https://drive.google.com/file/d/1XH4fLsdduAx7suTIQE3i20cL5fD_xIcj/view?usp=share_link), to explain it to the Bioportal team. 

### The new Goal

Make the portal metadata model the most complaint and consistent with our [Metadata curation guide](https://docs.google.com/document/d/1NHFNUjwOV7_aBrwNqDDgSshLTVewiZsKnFPLWuKc-xY/edit), so that we can reinforce its usage in the code for validation, UI/UX, Help  .....

### New Requirements

- [x] Technical: #409
- [ ] Curation: https://github.com/agroportal/project-management/issues/381

### References

- [Metadata curation references ](https://doc.jonquetlab.lirmm.fr/share/0c7f3651-6b40-47c2-94bf-8044b75cc922)
- [Metadata curation guide](https://docs.google.com/document/d/1NHFNUjwOV7_aBrwNqDDgSshLTVewiZsKnFPLWuKc-xY/edit)
- [2018 presentation video](https://drive.google.com/file/d/1XH4fLsdduAx7suTIQE3i20cL5fD_xIcj/view?usp=share_link)

**Comment by hibadjebabria169** [comment]
## **In the [metadata curation guide](https://docs.google.com/document/d/1NHFNUjwOV7_aBrwNqDDgSshLTVewiZsKnFPLWuKc-xY/edit?usp=sharing) :**
We have designed a Template to list all the properties in AgroPortal which are 130 properties so far,

The properties are classified according to their appearance in the interface which gives the following categories: _General, Licensing, Description, Date, People and Organisations, Community, Usage, Methodology, Object description properties, Links, Relations, Content, Media, Metrics and Configuration metadata._

Each property has its `label` and its `short URI` which correspond respectively to its label and its namespace in the interface,  labels (`links`) in the different possible vocabularies that define the same property, and the `definitions` of this property in these vocabularies (using the MOD2.0 and MOD1.4 working document).

To guarantee the validity of the metadata, we have added `validators` that it undergoes when being displayed in the interface as well as the recommended values of this particular property so that the user can introduce accurate and uniform values with all the other values in AgroPortal.

The properties are followed by` curation rules` that are intended for the curators of the portal and tasks to do for the values already existing in AgroPorta.  They will be converted into issues on GitHub and referenced here https://github.com/agroportal/project-management/issues/381

We were also interested in the statistical side, so we defined the `filling ratio` that represents the percentage of ontologies that have a value for a given property, this calculation will be done automatically in the backend (see https://github.com/ontoportal-lirmm/ontologies_api/issues/30).

Finally, we specified the `dependencies between some properties` such as dates and versions.

**Comment by jonquet** [comment]
Might need to open another issue to asses and tracjk changes wrt metadata extraction process.

**Comment by syphax-bouazzouni** [comment]
> Might need to open another issue to asses and tracjk changes wrt metadata extraction process.

See https://github.com/agroportal/project-management/issues/340
