### ISSUE TITLE
People' fields should be an array of a complex FOAF object 

### ISSUE THREAD

**Issue by hibadjebabria169** [agroportal/project-management#380]
The idea here is that when input is a person, its fields ( name,orcid...) will be converted into a FOAF object where each item has 2 fields : name , orcid

**Comment by jonquet** [comment]
Indeed strucure wull be certainly based on foaf:Person

In preparation of this we need to curate all the people properties: bpm:contact, omv:hasCreatoromv, hasContributor, pav:curatedBy, schema:translator and also organization/person : dcterms:publisher, foaf:fundedBy, omv:endorsedBy
to respect the format preonised by the person_validator: 

person_validator : 
format_validator = string+patternFollowing pattern"firstname surname (ORCID)”ORCID must be a number, not a URL e.g., 0000-0002-2404-1582 rather than http://orcid.org/0000-0002-2404-1582  Multiple values can be listed separated by commas

**Comment by jonquet** [comment]
This will need to be addressed also when merging with EcoPortal
