### ISSUE TITLE
Edition de la métadonnées en échec supprime le lien a la soumission

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#424]
Apres une edition en échec de la métadonnées de GR-TAX (changement de la propriété open search description) ... un autre edition (ajouter les s aux liens HTTP de la métadonnées) ... a provoquer une déconnection entre l'ontologie et sa submission. 

A noter: GR-TAX avait une seule submisison. 

<img width="593" alt="Capture d’écran 2023-06-05 à 15 10 06" src="https://github.com/agroportal/project-management/assets/7379183/cb7a8f8e-68cc-4544-9937-a1c8bf978275">

**Comment by syphax-bouazzouni** [comment]
Fixed 
<img width="1251" alt="image" src="https://github.com/agroportal/project-management/assets/29259906/9ab6d081-6509-418f-8462-853894324e70">
And don't know the original cause, but the issue was that the submission lost its connection to the ontology. When we do `ontology.submissions` is an empty array  and `submission.ontology `is null.

If you can't reproduce it @jonquet , please close this.

**Comment by jonquet** [comment]
Was not able to duplicate but realise recently the submission for GR-TAX is gone again.

**Comment by syphax-bouazzouni** [comment]
I still can see it, is it not a cache issue on your side?

**Comment by jonquet** [comment]
Indeed, I can see the submision too now. 
Something happenned. 
Just to proof I am not crazy, I copy/paste the admin page row for this onto (will certainly go away at next refresh): 
<img width="1496" alt="Capture d’écran 2023-09-13 à 21 14 10" src="https://github.com/agroportal/project-management/assets/7379183/15ebd348-be35-43fb-be9f-cda6bfd55c75">

To be continued

**Comment by syphax-bouazzouni** [comment]
No, the submission was indeed lost, since last June. I restored it today using the ncbo_cron console.
You did not see it after because the cache did not get updated on your side.
And the issue was that if you save a submission with its property ontology set as null it will become an orphan submission that we can't find or attach to an existent ontology. (But I don't know where in the UI this could happen)

**Comment by jonquet** [comment]
Thank for details. Good to me so.
