### ISSUE TITLE
submission date is always the same on stageportal

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#488]
I had to manually edit the metadata to set it to the correct date. 
The date automatically added by stageportal is the same as the creation date, which is wrong and very disturbing when submitting a new version. The impression is that the last submission failed (as the date remains the same) 
I don't know if it is the same on Agroportal

**Comment by jonquet** [comment]
J'ai observé un peu pareil aussi. @saubin78 tu as l'exemple negatif sur Stage et le positif the Agro ?

**Comment by saubin78** [comment]
Finally, on stageportal, it looks like it is the same date as the previous submission.
Submission #10 for MILKOLIGO was done on 22/02 and stamped 21/02 (yesterday I changed the submission date manually for submissions  #8 and #9)
![image](https://github.com/agroportal/project-management/assets/18008698/de499173-dde2-4815-bfcb-b0289c53d220)

**Comment by saubin78** [comment]
I don't have an example for agroportal (and no new submission to add for now)
Note that INRAE thesaurus is not a good example as I submitted all the versions the same day.

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/576

![image](https://github.com/agroportal/project-management/assets/29259906/b90ebe34-0fff-4f1f-acec-af10227648ef)


the issue was that we copied all metadata from one submission to another, except some, defined in the list below, the solution was to add `creationDate` to that list. 
```ruby 
    attr_to_not_copy = [:versionIRI, :version, :deprecated, :valid, :curatedOn,
                        :pullLocation, :metadataVoc, :hasPriorVersion, :creationDate,
                        :submissionStatus]
```


We will need to curate the corrupted metadata, manually, I created this issue to track that https://github.com/agroportal/project-management/issues/513

**Comment by jonquet** [comment]
I might suggest a hotfix in prod for this one.
