### ISSUE TITLE
PO - ontology unfindable despite uploading.

### ISSUE THREAD

**Issue by user34ngrau** [agroportal/project-management#492]
Problem: "PO" (acronym of Plant Ontology) is unfindable in the search bar. If I start the search, "PO" appears at the 8th position. 
Hyptohesis: The problem is maybe due to the shortness of its acronym. 
Idea of solution: Would be nice if we can install a minimum of 3/4 lettres for an acronym to avoid cases like this one and prevent to make an ontology unfindable

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/575

in the search box, always first.
<img width="592" alt="image" src="https://github.com/agroportal/project-management/assets/29259906/05481678-a9b5-4049-b1e8-532647bfd87d">

On the browse page, the first or second proposition.
<img width="1316" alt="image" src="https://github.com/agroportal/project-management/assets/29259906/3ffb88a3-d0fb-464a-b864-2bcb795c8733">
