### ISSUE TITLE
404 Errors in Portal Post v2.8.0 Release

### ISSUE THREAD

**Issue by Bilelkihal** [agroportal/project-management#553]
### Description
After releasing version 2.8.0, we are experiencing multiple 404 errors throughout the portal.

### Potential Cause
The issue seems to be related to the following call in the UI:
`LinkedData::Client::Models::Ontology.find_by_acronym(ontology).first`
This call is returning an array instead of a hash.

**Comment by syphax-bouazzouni** [comment]
what is the content if this array?

**Comment by Bilelkihal** [comment]
Now I tried many times but I can't reproduce the error, but the last time I used the master of `ontologies_api_ruby_client` instead of development in my local environnement. I got that error and the content of the array was another array and then the hash of the ont,
the expected structure is one array, but we I got a double one

**Comment by syphax-bouazzouni** [comment]
This issue was resolved in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/632 (specifically this commit https://github.com/ontoportal-lirmm/ontologies_api_ruby_client/commit/f91c32d532e6109b7eaccd5fd2ef51fef2192d71) and deployed in production.
If you saw this error in your machine, it is surely because you have not done a git pull to get the latest version. 

But even in production, @jonquet saw this in production yesterday https://github.com/agroportal/project-management/issues/551#issuecomment-2135663340, which is strange. There may be another hidden case where this occurs.

**Comment by syphax-bouazzouni** [comment]
Do you know if this still happens or do we close? @jonquet @Bilelkihal

**Comment by jonquet** [comment]
I have not experienced it anymore except with LEXEAU but we are not sure of reasons with multiples edit/loading of the resource by the devolper

**Comment by Bilelkihal** [comment]
@syphax-bouazzouni 
My side, this issue has not recurred

**Comment by syphax-bouazzouni** [comment]
> I have not experienced it anymore except with LEXEAU but we are not sure of reasons with multiples edit/loading of the resource by the devolper

LEXEAU is fixed by this https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/645
