### ISSUE TITLE
Bug with classes export

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#596]
**Describe the bug**
It is not possible to export a class/concept in json-l, n-triples and turtle for https://agroportal.lirmm.fr/ontologies/MILKOLIGO (I've not tried other vocabularies)

**To Reproduce**
1. Go to '[...'](https://agroportal.lirmm.fr/ontologies/MILKOLIGO?p=classes&propertyid=http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fabstract&conceptid=http%3A%2F%2Fopendata.inrae.fr%2Fholooligo%2Foligo_245)
2. Click on '.button Json-ld ...' or other at the end of the page
4. See error : error message (see screenshot)

**Screenshots**
![image](https://github.com/user-attachments/assets/38175232-e8ac-46d6-8d47-8028f639dc36)

**Comment by jonquet** [comment]
A regarder le problème n'est visiblement pas que sur cette ontologie.

**Comment by syphax-bouazzouni** [comment]
Log 
![image](https://github.com/user-attachments/assets/e7f48965-6b59-4ef7-8218-daed8cf00fe4)

Already fixed in Stageportal with https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/141/commits/f0ce03563fd7e412301a2c687e02f07c33a24d06, will be deployed in the next release.
![image](https://github.com/user-attachments/assets/7c2fc16d-23a8-4383-8c89-55a2cee991bd)
